### PR TITLE
Fix deprecated warnings

### PR DESCRIPTION
**Pull request by jprjr**
Hi there - this PR removes some warnings about deprecated functions, I think the only remaining deprecated warning is macOS's warning about changing notification frameworks.

This also changes some parts of cmake to use `find_package(Qt5 COMPONENTS Core Gui)` instead of `find_package(Qt5Gui Qt5Core ...)`. This makes building with a pre-compiled Qt simpler, the user only needs to specify the `Qt5_DIR` variable. It also enables AUTOUIC and AUTORCC, adds .qrc files to the sources and removes the separate call to WRAP_UI.

### CODE REVIEW

**Comment by CDrummond** [comment]
Wow! That's a **lot** of changes - but looks good to me. Must have taken some time. Thanks for your effort, much appreciated.

**Comment by CDrummond** [comment]
Sorry, I have reverted this as it did not build on my Ubuntu 20.04 VM. Had errors such as `Qt::SkipParts` not in Qt namespace, they're still `QString::SkipParts`, issue with `Version` in TagLib, etc.

**Comment by jprjr** [comment]
No worries, I did all the linux testing on arch, which has the latest versions of everything. I suspect I may need to create some macros for older QT versions

**Comment by CDrummond** [comment]
I'm going to re-apply your changes then revert only the bits that don't compile. So, please hold off making any more changes until then.

**Comment by CDrummond** [comment]
I've reverted my revert :) - and then fix the build issues.

**Pull request merged**
