### PR TITLE
Haiku supporting code

### PR DESCRIPTION
**Pull request by miqlas**
WIP

### CODE REVIEW

**Comment by CDrummond** [comment]
Patch looks ok - quite small really :-) However, application_haiku is **very** similar to application_qt - as in it uses dbus. If you are linking with dbus - why not just use application_qt ??? Does haiku not support MPRIS? With your patch, the MPRIS support will still be built in - just not used to raise the window.

If you dont want DBUS - then you need to edit the top-level CMakeLists.txt to disable this (this already happens for UbuntuTouch, Windows, and Mac). Then in application_haiku loadFiles() could just be an empty function.

**Comment by miqlas** [comment]
Please, do not merge yet, it have serious bugs.

**Comment by miqlas** [comment]
The changes in support/utils.h resurrected the bug:

`MpdLibraryDb init 0x185c89e8 "/library/__config_settings_mpd_socket_6600.sql" "MPD"`

There is no path like that on Haiku.

The same with `/online` and `/podcasts`.

I don't really understand how your code selects the db and cache paths, but my changes didn't made it better. Please, help me if you can.

**Comment by miqlas** [comment]
I just tested my old hack again : https://github.com/CDrummond/cantata/issues/909#issuecomment-258694285
And created 2 ramdisk (online and podcasts), so they becomes /online and /podcasts. Now mpd, jamendo, magnitude and the podcasts works (it crashed before), but SoundCloud isn't.

**Comment by CDrummond** [comment]
No updates - so closing.

**Pull request closed without merging**
