### PR TITLE
Compiling with gcc5 and Qt5 requires -fPIC for some code

### LINKED ISSUE #827: Fails to build with gcc5 if Qt5 was compiled with reduce-relocations
In qglobal.h you can find following code:
```
#if !defined(QT_BOOTSTRAPPED) && defined(QT_REDUCE_RELOCATIONS) && defined(__ELF__) && \
    (!defined(__PIC__) || (defined(__PIE__) && defined(Q_CC_GNU) && Q_CC_GNU >= 500))
#  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
         "Compile your code with -fPIC (-fPIE is not enough)."
#endif
```

Because of that `set(CMAKE_CXX_FLAGS "${Qt5Widgets_EXECUTABLE_COMPILE_FLAGS}")` is not enough.

I'm not sending PR request for that because I'm not sure if it's ok to add -fPIC globally.

The errors are following:
```
cd /var/tmp/portage/media-sound/cantata-2.0.0/work/cantata-2.0.0_build/3rdparty/solid-lite && /usr/lib64/qt5/bin/moc @/var/tmp/portage/media-sound/cantata-2.0.0/work/cantata-2.0.0_build/3rdparty/solid-lite/moc_opticaldrive.cpp_parameters
[  1%] Generating moc_storagevolume.cpp
In file included from /usr/include/qt5/QtCore/qiodevice.h:37:0,
                 from /usr/include/qt5/QtCore/QIODevice:1,
                 from /var/tmp/portage/media-sound/cantata-2.0.0/work/cantata-2.0.0_build/3rdparty/qtiocompressor/../../../cantata-2.0.0/3rdparty/qtiocompressor/qtiocompressor.h:50,
                 from /var/tmp/portage/media-sound/cantata-2.0.0/work/cantata-2.0.0_build/3rdparty/qtiocompressor/moc_qtiocompressor.cpp:9:
/usr/include/qt5/QtCore/qglobal.h:1090:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
    ^
cd /var/tmp/portage/media-sound/cantata-2.0.0/work/cantata-2.0.0_build/3rdparty/solid-lite && /usr/lib64/qt5/bin/moc @/var/tmp/portage/media-sound/cantata-2.0.0/work/cantata-2.0.0_build/3rdparty/solid-lite/moc_storagevolume.cpp_parameter
```

```
cd /var/tmp/portage/media-sound/cantata-2.0.0/work/cantata-2.0.0_build/3rdparty/solid-lite && /usr/lib64/qt5/bin/moc @/var/tmp/portage/media-sound/cantata-2.0.0/work/cantata-2.0.0_build/3rdparty/solid-lite/moc_deviceinterface.cpp_parameters
In file included from /usr/include/qt5/QtCore/qnamespace.h:37:0,
                 from /usr/include/qt5/QtCore/qobjectdefs.h:41,
                 from /usr/include/qt5/QtCore/qobject.h:40,
                 from /usr/include/qt5/QtCore/qthread.h:37,
                 from /usr/include/qt5/QtCore/QThread:1,
                 from /var/tmp/portage/media-sound/cantata-2.0.0/work/cantata-2.0.0_build/support/../../cantata-2.0.0/support/thread.h:27,
                 from /var/tmp/portage/media-sound/cantata-2.0.0/work/cantata-2.0.0_build/support/moc_thread.cpp:9:
/usr/include/qt5/QtCore/qglobal.h:1090:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
    ^
[  0%] Generating moc_devicemanager_p.cpp
```

```
make[2]: Leaving directory '/var/tmp/portage/media-sound/cantata-2.0.0/work/cantata-2.0.0_build'
make -f support/CMakeFiles/support-core.dir/build.make support/CMakeFiles/support-core.dir/build
In file included from /usr/include/qt5/QtCore/qiodevice.h:37:0,
                 from /usr/include/qt5/QtCore/QIODevice:1,
                 from /var/tmp/portage/media-sound/cantata-2.0.0/work/cantata-2.0.0/3rdparty/qtiocompressor/qtiocompressor.h:50,
                 from /var/tmp/portage/media-sound/cantata-2.0.0/work/cantata-2.0.0/3rdparty/qtiocompressor/qtiocompressor.cpp:47:
/usr/include/qt5/QtCore/qglobal.h:1090:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
    ^
make[2]: Entering directory '/var/tmp/portage/media-sound/cantata-2.0.0/work/cantata-2.0.0_build'
```

### PR DESCRIPTION
**Pull request by Civil**
gcc5 sometimes emits copy realocations when compiling with
    -fPIE. >= Qt5.4.2 made that not possible.

To fix this, make use of cmake's ability to add fPIC
    when necessary.

More info: https://bugreports.qt.io/browse/QTBUG-45755

Fixes #827

### CODE REVIEW

**Comment by CDrummond** [comment]
Thanks for this. Are you saying that Qt5Widgets_EXECUTABLE_COMPILE_FLAGS is no longer required? Or should I leave that in, and have both?

**Comment by Civil** [comment]
https://codereview.qt-project.org/#/c/113254/2/src/corelib/Qt5CoreConfigExtras.cmake.in - it looks like it's replacement for Qt5Widgets_EXECUTABLE_COMPILE_FLAG. Not sure why docs are still mentioning EXECUTABLE_COMPILE_FLAG, cause Qt5_POSITION_INDEPENDENT_CODE is there since Qt 5.2 or even earlier.

**Comment by CDrummond** [comment]
But thats for Qt5Core_EXECUTABLE_COMPILE_FLAGS  - not sure if this is the same as Qt5Widgets_EXECUTABLE_COMPILE_FLAGS ?

**Comment by Civil** [comment]
Well, I don't have answer for that, sorry.

**Comment by Civil** [comment]
Actually I don't think it's possible to build QtCore and QtWidgets with different options for reduce-reallocations, but I don't have proofs for that.

**Comment by CDrummond** [comment]
Perhaps it should be:

    if (Qt5_POSITION_INDEPENDENT_CODE)
        set(CMAKE_POSITION_INDEPENDENT_CODE ON)
    else(Qt5_POSITION_INDEPENDENT_CODE)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${Qt5Widgets_EXECUTABLE_COMPILE_FLAGS}")
    endif (Qt5_POSITION_INDEPENDENT_CODE)


???

**Comment by Civil** [comment]
As you are also linking it with QtCore and you can't compile some parts of Qt with reduce-realloc and some other parts without, so I think you won't need to have "else" clause.

Though I've also got some insight about even better way to fix that, but it'll require much more changes and in the end will do the same. It's to migrate to imported targets.

**Comment by CDrummond** [comment]
The reason for the else part is for older gcc/qt5 versions. Qt5Widgets_EXECUTABLE_COMPILE_FLAGS was needed to fix compilation on some systems. 

I'm not sure as to whether Qt5_POSITION_INDEPENDENT_CODE is present for these???

**Comment by Civil** [comment]
Qt5_POSITION_INDEPENDENT_CODE is present since Qt5.2.1 or something like that, so most probably all the potential users will have it defined.

As about Qt5Widgets_EXECUTABLE_COMPILE_FLAGS - well, actually it most probably won't hurt if I'll modify the PR and just put it unconditionally (it'll be overrided by Qt5_POSITION_INDEPENDENT_CODE where needed and in case there is actually a problem that can be solved with extra cflags it's still be solved). So I'll modify the PR later today or tomorrow.

**Comment by CDrummond** [comment]
I've committed the change I proposed, so no need for merge. But thanks for this.

**Pull request closed without merging**
