### PR TITLE
Add custom notification formatting

### PR DESCRIPTION
**Pull request by droserasprout**
screenshot_20180224_171543
screenshot_20180224_171619
Is song.cpp right place to include format method?
I'm not sure if bunch of replaces is the right way to format strings. Performance seems to be acceptable tho. I also need your help with formatting track length and dealing with empty fields - not a cpp guru at all :)

### CODE REVIEW

**Comment by droserasprout** [comment]
Speaking about empty fields it would be great to have something like mpc's --format option:
>The  []  operator is used to group output such that if no metadata delimiters are found or matched between [ and ], then none of the characters between [ and ] are output.

**Comment by CDrummond** [comment]
The dialog should be something like:

```
Popup format (...):
Title: [ ]
Text: [ ]
```

The placeholders should be something like:
```
Title: [ %title% - %artist%  (e.g. title of song - artist)]
Text: [%album% (%year%) (e.g. name of album (year of album))]
```
i.e. show default settings.

However, to be honest I'm not sure I see the point in making this customisable, just seems a little over the top. Why would a user need to change this? I can understand you might not like it how it is now - so perhaps just propose a better title+text. But being configurable, not sure I want/like this. Not convinced.

**Comment by droserasprout** [comment]
Well maybe it's not the most popular feature but I've got used to it when using deadbeaf and Clementine players. This option greatly increases readability of notifications. However, the final decision is up to you.

**Comment by CDrummond** [comment]
Sorry, but I see this setting as over-kill. I have, however, updated the notifications so that they are the same format as the toolbar.

**Comment by droserasprout** [comment]
Nice! I'm ok with this. Thanks for your efforts!

**Pull request closed without merging**
